"""HTML Self-Knowledge Report generator for Mirror bot.

Generates a self-contained HTML report from Tier 1 profile + Tier 2 topics.
"""

import json
import logging
from datetime import date

logger = logging.getLogger("mirror.reports")


def generate_report_html(report_data, profile_text=None):
    """Generate a self-contained HTML report from structured report data.

    Args:
        report_data: dict with keys like identity, values, personality_patterns, etc.
        profile_text: optional raw Tier 1 profile text to include.

    Returns:
        HTML string.
    """
    today = date.today().strftime("%B %d, %Y")

    sections = [
        ("Identity", report_data.get("identity", "Insufficient data.")),
        ("Values", report_data.get("values", "Insufficient data.")),
        ("Personality Patterns", report_data.get("personality_patterns", "Insufficient data.")),
        ("Relationships", report_data.get("relationships", "Insufficient data.")),
        ("Goals", report_data.get("goals", "Insufficient data.")),
        ("Strengths", report_data.get("strengths", "Insufficient data.")),
        ("Blind Spots", report_data.get("blind_spots", "Insufficient data.")),
        ("Contradictions", report_data.get("contradictions", "Insufficient data.")),
        ("Evolution", report_data.get("evolution", "Insufficient data.")),
    ]

    one_thing = report_data.get("one_thing", "")

    sections_html = ""
    for title, content in sections:
        icon = _section_icon(title)
        sections_html += f"""
        <div class="card">
            <h2>{icon} {title}</h2>
            <p>{_escape(content)}</p>
        </div>"""

    one_thing_html = ""
    if one_thing:
        one_thing_html = f"""
        <div class="card highlight">
            <h2>The One Thing You Need to Hear</h2>
            <p>{_escape(one_thing)}</p>
        </div>"""

    raw_profile_html = ""
    if profile_text:
        raw_profile_html = f"""
        <div class="card raw-profile">
            <h2>Raw Profile Data</h2>
            <pre>{_escape(profile_text)}</pre>
        </div>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Mirror -- Self-Knowledge Report</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: #0a0a0a;
    color: #e0e0e0;
    line-height: 1.6;
    padding: 20px;
    max-width: 800px;
    margin: 0 auto;
}}
header {{
    text-align: center;
    padding: 40px 0 30px;
    border-bottom: 1px solid #222;
    margin-bottom: 30px;
}}
header h1 {{
    font-size: 28px;
    font-weight: 300;
    letter-spacing: 4px;
    text-transform: uppercase;
    color: #fff;
    margin-bottom: 8px;
}}
header .date {{
    font-size: 14px;
    color: #666;
}}
.card {{
    background: #111;
    border: 1px solid #1a1a1a;
    border-radius: 8px;
    padding: 24px;
    margin-bottom: 16px;
}}
.card h2 {{
    font-size: 16px;
    font-weight: 600;
    color: #999;
    text-transform: uppercase;
    letter-spacing: 1px;
    margin-bottom: 12px;
}}
.card p {{
    font-size: 15px;
    color: #ccc;
}}
.card.highlight {{
    border-color: #c9a227;
    background: #111100;
}}
.card.highlight h2 {{
    color: #c9a227;
}}
.card.highlight p {{
    color: #e0d8c0;
    font-size: 16px;
}}
.raw-profile pre {{
    font-size: 13px;
    color: #888;
    white-space: pre-wrap;
    word-wrap: break-word;
    line-height: 1.5;
}}
footer {{
    text-align: center;
    padding: 30px 0;
    color: #333;
    font-size: 12px;
}}
</style>
</head>
<body>
<header>
    <h1>Mirror</h1>
    <div class="date">Self-Knowledge Report -- {today}</div>
</header>
{one_thing_html}
{sections_html}
{raw_profile_html}
<footer>
    Generated by Mirror -- honest self-knowledge, no compromises.
</footer>
</body>
</html>"""

    return html


def parse_report_json(text):
    """Parse Claude's report response into a dict.

    Handles markdown code fences and partial JSON.
    """
    text = text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[1] if "\n" in text else text[3:]
        if text.endswith("```"):
            text = text[:-3]
        text = text.strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError as e:
        logger.error("Failed to parse report JSON: %s", e)
        return None


def _escape(text):
    """Basic HTML escaping."""
    return (text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;"))


def _section_icon(title):
    """Return a simple text icon for each section."""
    icons = {
        "Identity": "//",
        "Values": "//",
        "Personality Patterns": "//",
        "Relationships": "//",
        "Goals": "//",
        "Strengths": "//",
        "Blind Spots": "//",
        "Contradictions": "//",
        "Evolution": "//",
    }
    return icons.get(title, "//")
